"use client";

import { useState } from "react";

interface Props {
  tee: boolean;
  modelId?: string;
}

export function AttestationBadge({ tee, modelId }: Props) {
  const [open, setOpen] = useState(false);

  if (!tee) {
    return null;
  }

  return (
    <div className="relative inline-block">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        onBlur={() => setOpen(false)}
        className="inline-flex items-center gap-1.5 rounded-full border border-cyan-400/30 bg-cyan-400/10 px-2.5 py-1 text-xs font-medium text-cyan-200 transition hover:bg-cyan-400/15"
        aria-expanded={open}
        aria-label="Confidential compute information"
      >
        <span aria-hidden>🔒</span>
        <span>Confidential Compute</span>
      </button>
      {open ? (
        <div
          role="dialog"
          className="absolute left-0 top-full z-10 mt-2 w-72 rounded-lg border border-white/10 bg-[#0c1020] p-3 text-xs text-zinc-300 shadow-xl"
        >
          <p className="mb-1 font-semibold text-white">
            Hardware-isolated inference
          </p>
          <p>
            This answer was generated by a Chutes model running inside an Intel
            TDX confidential-compute enclave. The model operator cannot read the
            screenshot you shared.
          </p>
          {modelId ? (
            <p className="mt-2 break-all font-mono text-[10px] text-zinc-500">
              Model: {modelId}
            </p>
          ) : null}
          <p className="mt-2 text-[10px] text-zinc-500">
            Attestation proves the execution environment, not the AI&apos;s
            fairness or correctness.
          </p>
        </div>
      ) : null}
    </div>
  );
}
